"""SIP accounts of trainees (PRD 9.5).

Every student gets two PJSIP endpoints with one password: ``stu-<login>`` for the browser
softphone (WebRTC) and ``phone-<login>`` for a desk IP phone. The password is generated on
first use, stored encrypted in ``users.sip_password_enc`` and written in clear into the
endpoints file that the Asterisk container includes (``deploy/asterisk/pjsip.conf``); after a
change Asterisk is asked to reload ``res_pjsip`` through ARI.

The endpoint templates (codecs, DTLS, ICE) live in ``pjsip.conf``; the generated file only
names the accounts, so the templates stay reviewable in git.
"""

from __future__ import annotations

import base64
import hashlib
import os
import re
import secrets
from dataclasses import dataclass
from pathlib import Path

from cryptography.fernet import Fernet, InvalidToken
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.config import get_settings
from app.logging import get_logger
from app.models import Role, User
from app.telephony.settings import TelephonySettings

log = get_logger(__name__)

WEBRTC_PREFIX = "stu-"
PHONE_PREFIX = "phone-"
ENDPOINTS_FILE = "endpoints.conf"
PASSWORD_BYTES = 18  # 24 characters of URL-safe base64
_UNSAFE = re.compile(r"[^a-z0-9_-]")


@dataclass(frozen=True)
class SipAccount:
    login: str
    password: str

    @property
    def webrtc_endpoint(self) -> str:
        return WEBRTC_PREFIX + self.login

    @property
    def phone_endpoint(self) -> str:
        return PHONE_PREFIX + self.login


def endpoint_login(login: str) -> str:
    """PJSIP section names allow letters, digits, dash and underscore."""
    return _UNSAFE.sub("", login.lower())


def webrtc_endpoint(user: User) -> str:
    return WEBRTC_PREFIX + endpoint_login(user.login)


# ---------------------------------------------------------------- password storage


def _fernet() -> Fernet:
    # Fernet wants a 32-byte urlsafe key; derive it from the application secret so the
    # stand needs no second secret.
    key = hashlib.sha256(get_settings().secret_key.encode("utf-8")).digest()
    return Fernet(base64.urlsafe_b64encode(key))


def encrypt_password(password: str) -> str:
    return _fernet().encrypt(password.encode("utf-8")).decode("ascii")


def decrypt_password(token: str) -> str | None:
    try:
        return _fernet().decrypt(token.encode("ascii")).decode("utf-8")
    except (InvalidToken, ValueError):
        return None


def new_password() -> str:
    return secrets.token_urlsafe(PASSWORD_BYTES)


async def ensure_account(session: AsyncSession, user: User) -> tuple[SipAccount, bool]:
    """The user's SIP account and whether it was just created (flushed, not committed;
    after a creation the caller re-syncs the endpoints file)."""
    password = decrypt_password(user.sip_password_enc) if user.sip_password_enc else None
    created = False
    if password is None:
        password = new_password()
        user.sip_password_enc = encrypt_password(password)
        await session.flush()
        created = True
        log.info("sip account created", login=user.login)
    return SipAccount(login=endpoint_login(user.login), password=password), created


async def all_accounts(session: AsyncSession) -> list[SipAccount]:
    users = await session.scalars(
        select(User)
        .where(User.role == Role.student, User.sip_password_enc.is_not(None))
        .order_by(User.login)
    )
    accounts = []
    for user in users:
        password = decrypt_password(user.sip_password_enc or "")
        if password:
            accounts.append(SipAccount(login=endpoint_login(user.login), password=password))
    return accounts


# ---------------------------------------------------------------- endpoints file


def render_endpoints(accounts: list[SipAccount], config: TelephonySettings) -> str:
    """The PJSIP sections of all accounts; templates are defined in pjsip.conf."""
    lines = [
        "; Generated by the backend from the users table. Do not edit: the file is",
        "; rewritten whenever an account is created.",
        "",
    ]
    webrtc_allow = ",".join(config.webrtc_codecs)
    phone_allow = ",".join(config.phone_codecs)
    for account in accounts:
        lines += _endpoint_block(account.webrtc_endpoint, "webrtc", account, webrtc_allow)
        lines += _endpoint_block(account.phone_endpoint, "phone", account, phone_allow)
    return "\n".join(lines) + "\n"


def _endpoint_block(name: str, template: str, account: SipAccount, allow: str) -> list[str]:
    return [
        f"[{name}]({template}-endpoint)",
        f"auth={name}",
        f"aors={name}",
        f"callerid={account.login} <{name}>",
        "disallow=all",
        f"allow={allow}",
        "",
        f"[{name}]({template}-auth)",
        f"username={name}",
        f"password={account.password}",
        "",
        f"[{name}]({template}-aor)",
        "",
    ]


def endpoints_path() -> Path | None:
    folder = get_settings().asterisk_config_dir
    return Path(folder) / ENDPOINTS_FILE if folder else None


def write_endpoints(accounts: list[SipAccount], config: TelephonySettings) -> Path | None:
    """Writes the endpoints file atomically; ``None`` when no folder is configured."""
    path = endpoints_path()
    if path is None:
        return None
    path.parent.mkdir(parents=True, exist_ok=True)
    content = render_endpoints(accounts, config)
    tmp = path.with_suffix(".tmp")
    tmp.write_text(content, encoding="utf-8")
    os.replace(tmp, path)
    return path
